### ISSUE TITLE
Support for username/password?

### ISSUE THREAD

**Issue by srcLurker** [BioSehnsucht/pyelk#2]
The Elk M1 allows the ethernet connection to require a username/password for access. Are there plans to support allowing the use of a username/password for ethernet access with this library?

**Comment by BioSehnsucht** [comment]
I plan to support it as part of supporting the "secure port" mode, eventually. Currently it only supports unencrypted communication. Not sure when. Solving existing bugs and implementing some functionality/performance enhancements are my current priority, then getting the Home-Assistant side of things pulled into HASS proper. Though, once I've got the pending feature/bug fix release done I'll take another look at this and see if I can bump it up. When I started I didn't want to try and figure out how to combine SSL with untrusted certs and PySerial TCP connections, as there wasn't a lot of information I could find on it at the time and I wanted to try and get something functional quickly.  Since then I just haven't gone back to look at it ....

**Comment by srcLurker** [comment]
Thank you for the detailed answer!

I have been playing with the elk m1 and I have some simplistic code running that does the SSL portion + the username and password. I did it directly via the socket and the ssl library (https://docs.python.org/3.5/library/ssl.html) and have not tried PySerial before. If you would like, I could try creating a patch for a pull request to handle ssl and username/password and/or I can provide the connect() method I'm using as an example of connecting via ssl.

Please let me know if there is something I can do to help.

**Comment by BioSehnsucht** [comment]
I'd rather keep using PySerial if possible, but I've started separating out the connection logic so that if necessary to using SSL and Socket directly we can do that... originally the main code was too tightly coupled with assumptions of using PySerial for that to work. I don't think PySerial currently supports SSL, so I may end up having to re-implement all the functionality it gives to support SSL, or perhaps patch it into PySerial and submit a PR on it and hope it makes it into PySerial official in a timely fashion..

**Comment by srcLurker** [comment]
In looking at the PySerial documentation, it looks like it may be possible to extend the PySerial URL protocol via the url handler:

https://pythonhosted.org/pyserial/pyserial_api.html#serial.protocol_handler_packages

The documentation is a bit sparse, but it sounds like it would be possible to register an "elks" protocol to allow for a url of "elks://1.2.3.4:2601" which could then do the initial ssl wrap and username/password handshake. If this works the way the documentation implies, it seems like it would be a minor change to PyElk's Connection() class to register the new protocol handler and (hopefully) no changes to anything else.

I was thinking of giving it a try this weekend if it sounds reasonable.

**Comment by BioSehnsucht** [comment]
Ah, that might be perfect for getting a solution now, and not waiting on PySerial to merge a PR

**Comment by BioSehnsucht** [comment]
Looks like an example can be found at : 
https://github.com/pyserial/pyserial/blob/master/test/test_url.py
https://github.com/pyserial/pyserial/blob/master/test/handlers/protocol_test.py

This probably won't be too bad since can likely inherit from the built-in socket protocol and overload as needed.

**Comment by BioSehnsucht** [comment]
This is abandoned. Please use https://github.com/gwww/elkm1 / https://pypi.org/project/elkm1-lib/
